name=Things
version=1.6.0
author=Thije Robbe <thijer@hotmail.nl>
maintainer=Thije Robbe <thijer@hotmail.nl>
category=Communication
sentence=A library for setting up IoT devices for Thingsboard.
paragraph=Thingsboard offers a number of APIs that allow devices to interact with Thingsboard, of which the Gateway MQTT API and the device MQTT API are implemented here. 
architectures=*
depends=ArduinoJson (>=7.0.0), PubSubClient, Properties (>3.0.0)
url=https://github.com/thijer/Things
includes=ThingGateway.hpp,ThingDevice.hpp,ThingMQTT.hpp